#!/bin/bash

THIS="$(readlink -f "$(dirname "$0")")"

assert_installed() {
    if ! type -P "$1" &>/dev/null; then
        echo "Please install '$1'" >&2
        exit 1
    fi
}

# check requirements
assert_installed fzf
assert_installed tmux

rm -rf "$HOME/.funcs" || true
rm "$HOME/.tmux.conf" || true

ln -s "$THIS/funcs" "$HOME/.funcs"
ln -s "$THIS/files/tmux.conf"  "$HOME/.tmux.conf"

